apiVersion: v1
kind: ServiceAccount
metadata:
  name: kruize-sa
  namespace: "kube-system"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kruize-cr
  namespace: "kube-system"
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kruize-crb
subjects:
  - kind: ServiceAccount
    name: kruize-sa
    namespace: "kube-system"
roleRef:
  kind: ClusterRole
  name: kruize-cr
  apiGroup: rbac.authorization.k8s.io
